services:

  # MySQL Database Service
  mysqlv8:
    extends:
      file: docker-compose.yml
      service: mysqlv8

  # Django Service
  django:
    extends:
      file: docker-compose.yml
      service: django

  # ReactJS Frontend Service
  reactjs:
    extends:
      file: docker-compose.yml
      service: reactjs

  # Fake data generator
  databuilder:
    build:
      context: ./stack/databuilder
      dockerfile: Dockerfile
    container_name: databuilder-service
    volumes:
      - ./stack/databuilder:/app/databuilder
    depends_on:
      django:
        condition: service_started
    extra_hosts:
      - "localapi.oaexample.com:127.0.0.1"

  # Front-end end-to-end testing
  cypress:
    build:
      context: ./stack/cypress
      dockerfile: Dockerfile
    container_name: cypress-service
    volumes:
      - ./stack/cypress:/app/cypress
      - /tmp/.X11-unix:/tmp/.X11-unix # For GUI if needed
    environment:
      - DISPLAY=:99.0 # For Xvfb headless mode
    depends_on:
      reactjs:
        condition: service_started
    extra_hosts:
      - "localapi.oaexample.com:127.0.0.1"
      - "localhost.oaexample.com:127.0.0.1"

networks:
  default:
    name: my_oaexample_network

volumes:
  mysql-data:
