# Use an official Python 3.11 base image
WORKDIR /app

COPY . /app

# Clean pre-generated directories from contributor testing
RUN rm -rf "/app/stack/src/.venv" \
    && rm -rf ".github" \
    && rm -rf "/app/stack/test" \
    && rm -rf "/app/stack/cypress/node_modules" \
    && rm -rf "/app/stack/databuilder/node_modules" \
    && rm -rf "/app/stack/django/.venv" \
    && rm -rf "/app/stack/k6/results/*" \
    && rm -rf "/app/stack/reactjs/node_modules" \
    && rm -rf "/app/stack/cypress/node_modules" \
    && rm -rf "/app/stack/cypress/cypress/fixtures/*" \
    && rm -rf "/app/stack/cypress/cypress/downloads/*" \
    && rm -rf "/app/stack/cypress/cypress/screenshots/*" \
    && rm -rf "/app/stack/cypress/cypress/videos/*" \
    && rm -rf "/app/stack/cypress/cypress/e2e/examples" \
    && rm -rf "/app/stack/databuilder/node_modules" \
    && rm -rf "/app/stack/django/.venv" \
    && rm -rf "/app/stack/django/media/uploads" \
    && rm -rf "/app/stack/django/newproject_app/migrations/*"

# Make all scripts executable
RUN chmod +x /app/stack/*.sh

# Default command to keep container ready for execution
CMD ["bash"]
