import React from 'react';
import {Box,} from '@mui/material';
import {Command, StyledPaper, StyledTypography} from "../components/StyledComponents";
import EnvBuilder from "../components/EnvBuilder";

interface Task {
    description: string;
    link: string;
}

const tasks: Task[] = [
    {
        description: "Split Users from other EntityTypes",
        link: "https://github.com/eliataylor/objects-actions/blob/main/stack/databuilder/src/types.ts#L16",
    },
    {
        description: "Implement Django User Groups and Permissions",
        link: "https://github.com/eliataylor/object-actions/blob/main/stack/django/oaexample_app/permissions.py",
    },
    {
        description: "Implement React render checks against permissions like can_verb",
        link: "https://github.com/eliataylor/object-actions/blob/main/stack/reactjs/src/object-actions/types/access.tsx#L72",
    },
    {
        description:
            "Implement Cypress tests against permissions.json. Fixtures can be generated by Databuilder",
        link: "https://github.com/eliataylor/object-actions/blob/main/stack/cypress/cypress/support/permissions.json",
    },
    {
        description: "Finish K6 load tests",
        link: "https://github.com/eliataylor/object-actions/blob/main/stack/k6/localhost.js",
    },
    {
        description: "Generate empty Worksheets for given Object list",
        link: "https://github.com/eliataylor/object-actions/blob/main/src/generate.py#L26",
    },
    {
        description: "Generate Django/TypeScript directly from Google Sheets",
        link: "https://github.com/eliataylor/object-actions/blob/main/src/generate.py#L26",
    },
    {
        description: "Drupal builder",
        link: "https://github.com/eliataylor/object-actions/blob/main/src/generate.py#L26",
    },
    {
        description: "KeystoneJS builder",
        link: "https://github.com/eliataylor/object-actions/blob/main/src/generate.py#L26",
    },
];

const Extend: React.FC = () => {

    return (
        <Box>
            <StyledTypography variant="h1">Extend</StyledTypography>
            <StyledTypography variant="subtitle1">
                This will check out the source, clone the entire stack, and renaming everything according to your .env
                settings below
            </StyledTypography>


            <StyledPaper>
                <Command command="git clone git@github.com:eliataylor/object-actions.git"
                         help={<>
                             <b>or</b> if you get SSL errors, use
                             <code> <em>git clone https://github.com/eliataylor/object-actions.git</em></code>
                         </>}
                />


                <Command command="cd object-actions"/>
            </StyledPaper>

            <StyledPaper>
                <Command command="cp .env .env.myproject"/>
            </StyledPaper>

            <StyledPaper>
                <StyledTypography variant="subtitle2" sx={{mb:3}}>
                    Edit your .env.myproject
                </StyledTypography>
                <EnvBuilder/>
            </StyledPaper>

            <StyledPaper>
                <Command command="./clone.sh --env .env.myproject"/>
            </StyledPaper>

            <StyledPaper>
                <Command command="cd STACK_PATH"/>
            </StyledPaper>

            <StyledPaper>
                <Command command="docker-compose up --build -d"/>
            </StyledPaper>

        </Box>
    );
};

export default Extend;
